image: openjdk:11

stages:
  - build
  - test
  - test Java 8
  - test Java 11
  - test Java 13

cache:
  paths:
    - .gradle
    - .gradle_home

build:
  stage: build
  artifacts:
    expire_in: 30 days
    paths:
      - build
  script:
    - mkdir -p .gradle_home
    - ./gradlew --no-daemon --info --full-stacktrace --gradle-user-home "$PWD/.gradle_home" classes testClasses

Run Checks:
  stage: test
  needs: ["build"]
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh check

CentOS 6 OpenJDK 8:
  stage: test Java 8
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos6-x64:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

CentOS 6 OpenJDK 11:
  stage: test Java 11
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos6-x64:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

CentOS 6 OpenJDK 13:
  stage: test Java 13
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos6-x64:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

CentOS 7 OpenJDK 8:
  stage: test Java 8
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos7:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

CentOS 7 OpenJDK 11:
  stage: test Java 11
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos7:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

CentOS 7 OpenJDK 13:
  stage: test Java 13
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos7:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Ubuntu 16.04 AdopOpenJDK 8:
  stage: test Java 8
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu16.04:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Ubuntu 16.04 AdopOpenJDK 11:
  stage: test Java 11
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu16.04:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Ubuntu 16.04 AdopOpenJDK 13:
  stage: test Java 13
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu16.04:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Ubuntu 18.04 AdopOpenJDK 8:
  stage: test Java 8
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu18.04:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Ubuntu 18.04 AdopOpenJDK 11:
  stage: test Java 11
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu18.04:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Ubuntu 18.04 AdopOpenJDK 13:
  stage: test Java 13
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu18.04:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Debian Stretch AdopOpenJDK 8:
  stage: test Java 8
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-stretch:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Debian Stretch AdopOpenJDK 11:
  stage: test Java 11
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-stretch:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Debian Stretch AdopOpenJDK 13:
  stage: test Java 13
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-stretch:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Debian Buster AdopOpenJDK 8:
  stage: test Java 8
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-buster:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Debian Buster AdopOpenJDK 11:
  stage: test Java 11
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-buster:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

Debian Buster AdopOpenJDK 13:
  stage: test Java 13
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-buster:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh
